export const FILE_PANEL_WIDTH = 224;
export const FILE_PANEL_COLLAPSED_WIDTH = 14;
export const FILE_PANEL_GAP = 16;

export const INSIGHTS_PANEL_WIDTH = 320;
export const INSIGHTS_PANEL_COLLAPSED_WIDTH = 18;
